global using ResumeProfile.FrameWork.Common;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata;
global using ResumeProfile.Domain.Entities.Common;
global using System.Security.Cryptography;
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using ResumeProfile.Domain.Entities;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using ResumeProfile.Infrastructure.Persistence;
global using ResumeProfile.Domain.Entities.IdentityEntities;
global using ResumeProfile.Domain.Entities.Loggers;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using ResumeProfile.Infrastructure.Common;

